[unstable]
codegen-backend = true
[profile.rustro]
inherits = "release"
codegen-backend = "cranelift"

[target.x86_64-pc-windows-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-Zcodegen-backend=cranelift"
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold"
]